export const apiRoutes = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    sessions: '/auth/sessions',
    revokeSession: (id: string) => `/auth/sessions/${id}`,
  },
  projects: {
    list: '/projects',
    detail: (id: string) => `/projects/${id}`,
    analytics: (id: string) => `/projects/${id}/analytics`,
    archive: (id: string) => `/projects/${id}/archive`,
  },
  dailyReports: {
    list: '/daily-reports',
    detail: (id: string) => `/daily-reports/${id}`,
    create: '/daily-reports',
    pdf: (id: string) => `/daily-reports/${id}/pdf`,
  },
  brigades: { list: '/brigades' },
  employees: { list: '/employees' },
  warehouses: { list: '/warehouses' },
  inventory: {
    items: '/inventory/items',
    transactions: '/inventory/transactions',
    receipts: '/inventory/receipts',
    stats: '/inventory/stats',
  },
  attendance: { list: '/attendance' },
  analytics: { overview: '/analytics/overview' },
  payroll: {
    preview: '/payroll/preview',
    list: '/payroll',
    detail: (id: string) => `/payroll/${id}`,
    close: '/payroll/close',
    addLine: (id: string) => `/payroll/${id}/lines`,
    addPayment: (id: string) => `/payroll/${id}/payments`,
  },
  finance: {
    expenses: '/finance/expenses',
    incomes: '/finance/incomes',
    pnl: '/finance/pnl',
    timeseries: '/finance/timeseries',
  },
  ai: {
    projectBrief: (id: string) => `/ai/projects/${id}/brief`,
    insights: '/ai/insights',
    insightsScan: '/ai/insights/scan',
  },
  documents: {
    list: '/documents',
    presign: '/documents/presign',
    create: '/documents',
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id: string) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
  },
  reports: {
    payrollXlsx: '/reports/payroll.xlsx',
    pnlXlsx: '/reports/pnl.xlsx',
    vehiclesXlsx: '/reports/vehicles.xlsx',
    payrollSlipPdf: (id: string) => `/reports/payroll/${id}/slip.pdf`,
  },
  vehicles: {
    list: '/vehicles',
    create: '/vehicles',
    update: (id: string) => `/vehicles/${id}`,
    usages: '/vehicles/usages',
  },
} as const;

export const appRoutes = {
  login: '/login',
  dashboard: '/dashboard',
  projects: '/projects',
  projectDetail: (id: string) => `/projects/${id}`,
  brigades: '/brigades',
  employees: '/employees',
  warehouse: '/warehouse',
  finance: '/finance',
  payroll: '/payroll',
  analytics: '/analytics',
  vehicles: '/vehicles',
  reports: '/reports',
  settings: '/settings',
} as const;
