export const apiRoutes = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
    changePassword: '/auth/change-password',
    sessions: '/auth/sessions',
    revokeSession: (id: string) => `/auth/sessions/${id}`,
  },
  projects: {
    list: '/projects',
    detail: (id: string) => `/projects/${id}`,
    analytics: (id: string) => `/projects/${id}/analytics`,
    brigades: (id: string) => `/projects/${id}/brigades`,
    archive: (id: string) => `/projects/${id}/archive`,
    members: (id: string) => `/projects/${id}/members`,
    memberBulk: (id: string) => `/projects/${id}/members/bulk`,
    member: (id: string, employeeId: string) => `/projects/${id}/members/${employeeId}`,
  },
  dailyReports: {
    list: '/daily-reports',
    detail: (id: string) => `/daily-reports/${id}`,
    create: '/daily-reports',
    pdf: (id: string) => `/daily-reports/${id}/pdf`,
    draft: '/daily-reports/draft',
  },
  workTemplates: {
    list: '/work-templates',
    create: '/work-templates',
    remove: (id: string) => `/work-templates/${id}`,
  },
  brigades: {
    list: '/brigades',
    ensureWarehouse: (id: string) => `/brigades/${id}/ensure-warehouse`,
    stats: (id: string) => `/brigades/${id}/stats`,
  },
  employees: { list: '/employees' },
  warehouses: {
    list: '/warehouses',
    create: '/warehouses',
    remove: (id: string) => `/warehouses/${id}`,
  },
  suppliers: {
    list: '/suppliers',
    detail: (id: string) => `/suppliers/${id}`,
    create: '/suppliers',
    update: (id: string) => `/suppliers/${id}`,
    remove: (id: string) => `/suppliers/${id}`,
  },
  purchaseOrders: {
    list: '/purchase-orders',
    detail: (id: string) => `/purchase-orders/${id}`,
    create: '/purchase-orders',
    update: (id: string) => `/purchase-orders/${id}`,
    approve: (id: string) => `/purchase-orders/${id}/approve`,
    order: (id: string) => `/purchase-orders/${id}/order`,
    receive: (id: string) => `/purchase-orders/${id}/receive`,
    cancel: (id: string) => `/purchase-orders/${id}/cancel`,
  },
  inventory: {
    items: '/inventory/items',
    balances: '/inventory/balances',
    transactions: '/inventory/transactions',
    receipts: '/inventory/receipts',
    stats: '/inventory/stats',
    movements: '/inventory/movements',
    movementsBatch: '/inventory/movements/batch',
    reverseMovement: (id: string) => `/inventory/movements/${id}/reverse`,
    transfers: '/inventory/transfers',
    transferDetail: (id: string) => `/inventory/transfers/${id}`,
    transferShip: (id: string) => `/inventory/transfers/${id}/ship`,
    transferReceive: (id: string) => `/inventory/transfers/${id}/receive`,
    transferCancel: (id: string) => `/inventory/transfers/${id}/cancel`,
    stockCounts: '/inventory/stock-counts',
    stockCountDetail: (id: string) => `/inventory/stock-counts/${id}`,
    stockCountLines: (id: string) => `/inventory/stock-counts/${id}/lines`,
    stockCountSubmit: (id: string) => `/inventory/stock-counts/${id}/submit`,
    stockCountApprove: (id: string) => `/inventory/stock-counts/${id}/approve`,
    stockCountCancel: (id: string) => `/inventory/stock-counts/${id}/cancel`,
    reportsTurnover: '/inventory/reports/turnover',
    reportsAbc: '/inventory/reports/abc',
    reportsRefresh: '/inventory/reports/refresh',
    reportsBalancesXlsx: '/inventory/reports/balances.xlsx',
    reportsMovementsXlsx: '/inventory/reports/movements.xlsx',
    reportsPurchasesXlsx: '/inventory/reports/purchases.xlsx',
    reservations: '/inventory/reservations',
    reservationDetail: (id: string) => `/inventory/reservations/${id}`,
    reservationRelease: (id: string) => `/inventory/reservations/${id}/release`,
  },
  attendance: { list: '/attendance' },
  analytics: { overview: '/analytics/overview', company: '/analytics/company' },
  payroll: {
    preview: '/payroll/preview',
    list: '/payroll',
    detail: (id: string) => `/payroll/${id}`,
    close: '/payroll/close',
    addLine: (id: string) => `/payroll/${id}/lines`,
    addPayment: (id: string) => `/payroll/${id}/payments`,
  },
  finance: {
    expenses: '/finance/expenses',
    incomes: '/finance/incomes',
    pnl: '/finance/pnl',
    timeseries: '/finance/timeseries',
    breakdown: '/finance/breakdown',
    projects: '/finance/projects',
    operations: '/finance/operations',
    debts: '/finance/debts',
    debt: (id: string) => `/finance/debts/${id}`,
    debtPayments: (id: string) => `/finance/debts/${id}/payments`,
    debtPayment: (id: string, paymentId: string) =>
      `/finance/debts/${id}/payments/${paymentId}`,
  },
  ai: {
    projectBrief: (id: string) => `/ai/projects/${id}/brief`,
    insights: '/ai/insights',
    insightsScan: '/ai/insights/scan',
    summarizeReport: '/ai/summarize-report',
  },
  documents: {
    list: '/documents',
    presign: '/documents/presign',
    create: '/documents',
  },
  notifications: {
    list: '/notifications',
    unreadCount: '/notifications/unread-count',
    markRead: (id: string) => `/notifications/${id}/read`,
    readAll: '/notifications/read-all',
  },
  reports: {
    payrollXlsx: '/reports/payroll.xlsx',
    pnlXlsx: '/reports/pnl.xlsx',
    vehiclesXlsx: '/reports/vehicles.xlsx',
    payrollSlipPdf: (id: string) => `/reports/payroll/${id}/slip.pdf`,
  },
  vehicles: {
    list: '/vehicles',
    create: '/vehicles',
    update: (id: string) => `/vehicles/${id}`,
    usages: '/vehicles/usages',
  },
} as const;

export const appRoutes = {
  login: '/login',
  dashboard: '/dashboard',
  /** Object-centered route (formerly `/projects`). */
  objects: '/objects',
  /** Object workspace landing — base URL for all object sub-routes. */
  objectDetail: (id: string) => `/objects/${id}`,
  objectReports:    (id: string) => `/objects/${id}/reports`,
  objectWarehouse:  (id: string) => `/objects/${id}/warehouse`,
  objectFinance:    (id: string) => `/objects/${id}/finance`,
  objectTeam:       (id: string) => `/objects/${id}/team`,
  objectAnalytics:  (id: string) => `/objects/${id}/analytics`,

  // Company-wide directories (linked from /company hub)
  company: '/company',
  brigades: '/brigades',
  employees: '/employees',
  warehouse: '/warehouse',
  vehicles: '/vehicles',

  // Consolidated company finance (linked from /finance hub)
  finance: '/finance',
  payroll: '/payroll',
  reports: '/reports',

  analytics: '/analytics',
  settings: '/settings',
} as const;
